const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: {
    // 'main' entry is handled by Angular CLI's default webpack config
    // We only need to define additional entry points.
    options: './src/main.options.ts',
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'options.html',
      template: './src/options.html',
      chunks: ['options', 'polyfills', 'styles', 'vendor'], // Ensure necessary chunks are included
      // polyfills, styles, vendor chunks are typically generated by Angular
    }),
  ],
}
