name: Deploy Privacy Policy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'sites/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow a GITHUB_TOKEN to be used to push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sites
